### ISSUE TITLE
Update new sentences translated

### ISSUE THREAD

**Issue by jconstanti** [deivids84/MA-XML-9.0-CATALAN#3]
Actual translation is out of date. We need refresh new translated sentences

**Comment by ingbrzy** [comment]
better to update V10 repo https://github.com/deivids84/MA-XML-10-CATALAN

**Comment by jconstanti** [comment]
How update repo and who can do It?

**Comment by jconstanti** [comment]
deivids84 remains missing!!!

Sent from Yahoo Mail on Android 
 
  On dl., de des. 10, 2018 at 13:47, ingbrzy<notifications@github.com> wrote:   
Closed #3.
