### ISSUE TITLE
MIUI 9.8.1 [MI8] Calendar failure Catalan Language

### ISSUE THREAD

**Issue by MaxiDave** [deivids84/MA-XML-9.0-CATALAN#4]
This MIUI version Calendar APP fails when the 'Add' button is pressed. Only for Catalan language, English works well. I attached the bug report.

Thank you in advance.
![Screenshot_2019-08-02-13-54-30-862_com miui bugreport](https://user-images.githubusercontent.com/26763246/62368893-3db66f00-b52e-11e9-8f59-abb7ae0472d3.jpg)

**Comment by ingbrzy** [comment]
solved
